---
- name: Render vault configuration file
  template:
    src: vault_server.hcl.j2
    dest: "{{ vault_conf_dir }}/vault_server.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0640'
  notify:
    - Restart vault service