---
- name: Install docker
  package:
    name: "{{ docker_package_name }}"
    state: present

- name: Render docker configuration
  template:
    src: daemon.json.j2
    dest: "{{ docker_daemon_config_path }}"

- name: Start docker service
  systemd:
    name: docker
    state: started
    enabled: yes