---
- name: Render consul configuration file
  template:
    src: consul.json.j2
    dest: "{{ consul_conf_dir }}/consul.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0640'
  notify:
    - Restart consul service